### ISSUE TITLE
你好，请问搭建这个用宝塔的话，还需要配置什么环境吗

### ISSUE THREAD

**Issue by yhoyh** [Elmge/search-start-page#1]

**Comment by suemor233** [comment]
抱歉之前比较忙一直没看到。
你需要安装 `git nodejs pnpm nginx`
先把项目 `clone` 下来然后执行依次 `pnpm i` `pnpm build`
然后在宝塔上点击 **添加站点**，把打包完 `build` 文件夹里面内容移动到 **网站目录** 里即可
